# Generated by Django 5.1.2 on 2024-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_qr',
            field=models.IntegerField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productousuario',
            name='id_qr',
            field=models.IntegerField(default=0, max_length=50, unique=True),
        ),
    ]
