# Generated by Django 5.1.2 on 2024-12-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_id_qr_alter_productousuario_id_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
    ]
