# Generated by Django 5.1.2 on 2024-12-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productousuario',
            name='cod_producto2',
            field=models.IntegerField(default=0),
        ),
    ]
